name: Auto-pull
on:
  push:
    branches:
      - staging # change to your branch name
jobs:
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          host: ${{ secrets.SERVER_IP }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # add your private key as a secret
      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: SSH into server and pull changes
        run: |
          ssh root@${{ secrets.SERVER_IP }} "cd /opt/apace/apace_staging/apace_repo && git pull && /etc/init.d/apace-server force-restart"
